name: ReBot CI - Native Java 17

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install -y build-essential libz-dev zlib1g-dev
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: package
      run: -|
        mvn clean package --no-transfer-progress --file pom.xml -Pnative -Dmaven.javadoc.skip=true -Dquarkus.native.container-build=true -DskipTests -Dnet.bytebuddy.experimental=true
  
